[package]
name = "diffable_derive"
version = "0.1.0"
authors = ["Aaron Cunningham <aa.cunningham@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = "0.15.26"
quote = "0.6.11"
